"""

Revision ID: 0d64bcb24b19
Revises: ab389bdccfb3
Create Date: 2025-04-12 12:47:17.364474

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d64bcb24b19"
down_revision: Union[str, None] = "ab389bdccfb3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "logs",
        "algorithm",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "logs",
        "algorithm",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
